server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force-response: true

logging:
  level:
    org.zalando.logbook: TRACE

spring:
  jpa:
    properties:
      hibernate:
        show_sql: false
        default_batch_fetch_size: 1000
    open-in-view: false
    hibernate:
      ddl-auto: none

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}


security:
  jwt:
    expire-length:
      access-token: 300000 # 5분
      refresh-token: 604800000 # 1주일
#
    secret-key: ${ACCESS_TOKEN_KEY}
    refresh-secret-key: ${REFRESH_TOKEN_KEY}
