server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force-response: true

logging:
  level:
    org.zalando.logbook: TRACE

spring:
  jpa:
    properties:
      hibernate:
        show_sql: false
        default_batch_fetch_size: 1000
    hibernate:
      ddl-auto: create
    open-in-view: false

  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
