name: code-koi api-server CI/CD

on:
  push:
    branches: ["master"]

permissions:
  contents: read

jobs:
  CI-CD:
    runs-on: ubuntu-latest
    steps:

      ## jdk setting
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      ## gradle build
      - name: Build with Gradle
        run: ./gradlew bootJar

      ## docker build & push to production
#      - name: Docker build & push to prod
#        if: contains(github.ref, 'master')
#        run: |
#          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
#          docker build -f Dockerfile-prod -t ${{ secrets.DOCKER_REPO }}/koi-api-server-prod .
#          docker push ${{ secrets.DOCKER_REPO }}/koi-api-server-prod

      ## docker build & push to master
      - name: Docker build & push to dev
        if: contains(github.ref, 'master')
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -f Dockerfile-dev -t ${{ secrets.DOCKER_REPO }}/koi-api-server-dev .
          docker push ${{ secrets.DOCKER_REPO }}/koi-api-server-dev

      ## deploy to production
#      - name: Deploy to prod
#        uses: appleboy/ssh-action@master
#        id: deploy-prod
#        if: contains(github.ref, 'master')
#        with:
#          host: ${{ secrets.HOST_PROD }}
#          username: ubuntu
#          key: ${{ secrets.PRIVATE_KEY }}
#          script: |
#            ./docker-run.sh

      ## deploy to develop
      - name: Deploy to dev
        uses: appleboy/ssh-action@master
        id: deploy-dev
        if: contains(github.ref, 'master')
        with:
          host: ${{ secrets.HOST_DEV }}
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            ./docker-run.sh